### ISSUE TITLE
Bug in Chapter I

### ISSUE THREAD

**Issue by hathix** [rainlash/lex-talionis#5]
Right after doing the tutorial (where you use Cleave to kill the two Fighters) and turning on the danger zone with X, I got this crash after I hit "Wait":

```
Main Crash get_cell() takes exactly 3 arguments (2 given)
Traceback (most recent call last):
  File "main.py", line 118, in <module>
    main()
  File "main.py", line 46, in main
    run(gameStateObj, metaDataObj)
  File "main.py", line 64, in run
    mapSurf, repeat = gameStateObj.stateMachine.update(eventList, gameStateObj, metaDataObj)
  File "/Users/neel/Git/lex-talionis/Code/StateMachine.py", line 195, in update
    update_output = self.state[-1].update(gameStateObj, metaDataObj)
  File "/Users/neel/Git/lex-talionis/Code/StateMachine.py", line 1846, in update
    did_something = gameStateObj.ai_current_unit.ai.act(gameStateObj)
  File "/Users/neel/Git/lex-talionis/Code/AI_fsm.py", line 198, in act
    if self.think(gameStateObj):
  File "/Users/neel/Git/lex-talionis/Code/AI_fsm.py", line 169, in think
    if self.inner_ai.update(gameStateObj):
  File "/Users/neel/Git/lex-talionis/Code/AI_fsm.py", line 841, in update
    my_path = self.getPath(target.position, gameStateObj, limit=limit)
  File "/Users/neel/Git/lex-talionis/Code/AI_fsm.py", line 886, in getPath
    self.pathfinder.set_goal_pos(goal_pos)
  File "/Users/neel/Git/lex-talionis/Code/AStar.py", line 176, in set_goal_pos
    self.end = self.get_cell(self.goalposition)
TypeError: get_cell() takes exactly 3 arguments (2 given)

Created save point at last turn change! Select Continue in Main Menu to load!

=== === === === === ===
Damn. Another bug :(
Quick! Copy this error log and send it to rainlash!
Or send the file "Saves/debug.log.1" to rainlash!
Thank you!
=== === === === === ===
```

**Comment by hathix** [comment]
It freezes and crashes on this screen: 
<img width="832" alt="screen shot 2018-06-27 at 10 06 26 pm" src="https://user-images.githubusercontent.com/728084/42008985-5f4b7412-7a56-11e8-8e07-8fb9caae3bdb.png">
